DWAPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.0

  max_vel_y: 0.0       # Set to 0.0 for non-holonomic (differential) robots

  max_trans_vel: 0.8   # Max speed when moving forward
  min_trans_vel: 0.1   # Min allowed translational velocity

  max_rot_vel: 1.5
  min_rot_vel: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.02

  stop_time_buffer: 0.2
  forward_point_distance: 0.325

  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  publish_traj_pc: true
  publish_cost_grid_pc: true

  holonomic_robot: false
